### ISSUE TITLE
End of file error (line 34 of main.f)

### ISSUE THREAD

**Issue by lokamigauti** [thiagogomesverissimo/csv2spe#1]
Dear Thiago, 

I've tried to run the compiled program using this batch commands:

> dir *.csv /b/s > passagem.dat
> pause
> (
> echo S 
> echo %~dp0passagem.dat
> ) | converte_xrf_spe.exe
> DEL passagem.dat
> pause

The output:

>  Do you have a file with file names?
>   No (N)    Yes (S)
> S
>   Write the contain the file names of csv files
> passagem.dat
> At line 34 of file main.f (unit = 103, file = 'passagem.dat')
> Fortran runtime error: End of file
> 
> Error termination. Backtrace:
> 
> Could not print backtrace: libbacktrace could not find executable to open
> #0  0x6f8aecb4
> #1  0x6f8a11ce
> #2  0x6f81fac4
> #3  0x6f8a2ba7
> #4  0x6f8ad597
> #5  0x6f8acef4
> #6  0x6f8c4258
> #7  0x6f89b1d5
> #8  0x403053
> #9  0x40316f
> #10  0x401287

The xrf's .csv files used are annexed.
The code were executed using GNU Fortran (MinGW.org GCC-6.3.0-1) 6.3.0

[xrf.zip](https://github.com/thiagogomesverissimo/csv2spe/files/5965122/xrf.zip)

**Comment by thiagogomesverissimo** [comment]
Did you use GNU Fortran on Windows or Linux?

**Comment by lokamigauti** [comment]
Windows 10.

**Comment by thiagogomesverissimo** [comment]
I do not have a win 10 here to test it.
But I tried in linux and it is working. 

Have you tried to convert one single file first?

**Comment by lokamigauti** [comment]
Yes, it is working well in single files. The problem seems to be related wth the addres list reading

**Comment by lokamigauti** [comment]
I used the sample files without success. Follow in annex the list.txt used.
[list.txt](https://github.com/thiagogomesverissimo/csv2spe/files/5966260/list.txt)

**Comment by thiagogomesverissimo** [comment]
ok, it is good, because the "core" is ok.

So, the problem is related to how windows handle end of line and end of file. 
Maybe some changes in fortran will be required...

**Comment by lokamigauti** [comment]
I made this change in the fortran code:
from:

> 	do i=1,500
> 	   print*, arq
> 	   read(103,'(a)',err=60)espec(i)
> 	   j=i
> 	enddo
>    60	close(103)

to

> 	do i=1,500
> 	   print*, arq
> 	   read(103,'(a)',end=60)espec(i)
> 	   j=i
> 	enddo
>    60	close(103)

The read function do not encounter an error situation, but a eof. I'll suggest a fork.

Thanks!
